-- AlterTable
ALTER TABLE "Holiday" ALTER COLUMN "start_date" SET DATA TYPE VARCHAR(255),
ALTER COLUMN "end_date" SET DATA TYPE VARCHAR(255);

-- AlterTable
ALTER TABLE "Semester" ALTER COLUMN "start_date" SET DATA TYPE VARCHAR(255),
ALTER COLUMN "end_date" SET DATA TYPE VARCHAR(255);
